WIP: ut-error deprecations
softwaregroup-bg/ut-codec-jsonrpc pull request #3
Opened 2018-09-19 12:26 UTC by Kristiyan-Todorov

2018-09-26 10:39 UTC, Kristiyan-Todorov commented
depends on changes in [ut-port-tcp](https://github.com/softwaregroup-bg/ut-port-tcp/pull/14)

2018-09-26 10:42 UTC, zetxx approved these changes

2018-09-28 05:48 UTC, kalinkrustev requested changes

2018-09-28 05:48 UTC, kalinkrustev commented on index.js
> +            throw this.errors['jsonRPCCodec.invalidJson.invalidVersion']({message: `Expected version ${this.version} but received ${json.jsonrpc}`});
Is this really needed ({message:X}), can it be simply (X) ?

2018-10-01 12:24 UTC, merged